name: quickbill_pk
description: QuickBill PK - Simple Invoice Generator for Small Businesses

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Local Database
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3   # Required for Windows/Linux/macOS desktop support
  path: ^1.9.0

  # PDF Generation
  pdf: ^3.10.8
  printing: ^5.12.0

  # Date & Number Formatting
  intl: ^0.19.0

  # Unique IDs
  uuid: ^4.4.0

  # Charts
  fl_chart: ^0.66.2

  # Icons
  cupertino_icons: ^1.0.6
  sqflite_common_ffi_web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
